### ISSUE TITLE
found invalid [totalNumberConsumedPercent] with value [0.21.3]

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/interaction-data#15]
Just noticed an error message "[totalNumberConsumedPercent] with value [0.21.3]" in import logs. 

@jsimons9 @tmitchell1 any idea what the correct value should be?

```
org.eol.globi.data.StudyImporterException: failed to parse key [totalNumberConsumedPercent] with value [0.21.3]
	at org.eol.globi.data.StudyImporterForGoMexSI2.doubleValueOrNull(StudyImporterForGoMexSI2.java:309)
	at org.eol.globi.data.StudyImporterForGoMexSI2.setSpecimenProperty(StudyImporterForGoMexSI2.java:336)
	at org.eol.globi.data.StudyImporterForGoMexSI2.createSpecimen(StudyImporterForGoMexSI2.java:319)
	at org.eol.globi.data.StudyImporterForGoMexSI2.addObservation(StudyImporterForGoMexSI2.java:262)
	at org.eol.globi.data.StudyImporterForGoMexSI2.addObservations(StudyImporterForGoMexSI2.java:185)
	at org.eol.globi.data.StudyImporterForGoMexSI2.importStudy(StudyImporterForGoMexSI2.java:105)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:86)
	at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:59)
	at org.eol.globi.tool.GitHubRepoCheck.main(GitHubRepoCheck.java:86)
Caused by: java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.eol.globi.data.StudyImporterForGoMexSI2.doubleValueOrNull(StudyImporterForGoMexSI2.java:306)
	... 8 more
```

**Comment by tmitchell1** [comment]
Fixed.

**Comment by jhpoelen** [comment]
Thanks!
